### ISSUE TITLE
[Install.Import] Allow adding multiple import statements

### ISSUE THREAD

**Issue by mateusfpleite** [jxxcarlson/elm-review-codeinstaller#24]
Currently, the Install.Import module only allows you to install one import expression at a time. Since we often have multiple imports in a module, it might be worth having another function `initMultiple` that would add a list of imports to the code simultaneously. This function could accept a String with the name of the target module and a list of tuples/records with the information for each import (e.g. ```{ moduleToImport : String, alias_ : Maybe String, exposedValues ​​: List String }```)

**Comment by jxxcarlson** [comment]
Yes, this is exactly what we need!  By coincidence, I had started sketching out how we might do this in a new local branch, but have not done much on it.  You have a very good sense for API design, so why don't you assign yourself to this issue?

Go for it!

**Comment by mateusfpleite** [comment]
Great, @jxxcarlson. I will start working on it as soon as possible!
